version: "3"
services:
  mongo:
    image: mongo
    container_name: mongo
    restart: always
  app:
    build: .
    environment: 
      MONGO_URL: mongodb://mongo/
    ports: 
      - 8000:8000
    depends_on: 
      - mongo


